config/routes.rb
Rails.application.routes.draw do
	resources :journels, only: [:create, :new, :index, :show] do
		member do
			get 'search_entries'
			get 'graph_data'
		end
		collection do
			get 'search'
		end
		resources :journel_entries, only: [:new, :create, :show, :edit, :update]
	end
	root 'journels#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/app_journel.rb
class AppJournel < ApplicationRecord
    has_many :journel_entries
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/journel_entry.rb
class JournelEntry < ApplicationRecord
    belongs_to :app_journel

    def updated?
        self.created_at != self.updated_at
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/journel_entries_controller.rb
class JournelEntriesController < ApplicationController
    before_action :set_journel_entry, only: [:edit, :show, :update]
    def new
        @journel = AppJournel.find_by(id: params[:journel_id])
    end

    def create
        journel = AppJournel.find_by(id: params[:journel_id])
        journel_entry = journel.journel_entries.new(journel_entry_params)
        
        if journel_entry.save
            flash[:success] = "Journal entry created"
        else
            flash[:danger] = "Something went wrong"
        end
        redirect_to journel_path(journel.id)
    end

    def show
    end

    def edit
    end

    def update
        if @journel_entry.update(journel_entry_params)
            flash[:success] = "Journal entry updated"
        else
            flash[:danger] = "Something went wrong"
        end
        redirect_to journel_journel_entry_path(@journel_entry.id)
    end

    private
    def journel_entry_params
        params.require(:journel_entry).permit(:title, :body)
    end

    def set_journel_entry
        @journel_entry = JournelEntry.find_by(id: params[:id])
    end
end

app/controllers/journels_controller.rb
class JournelsController < ApplicationController
  before_action :set_journel, only: [:show, :search_entries, :graph_data]
  before_action :set_session

  def index
  	@journels = AppJournel.all
  end

  def new
  end
  
  def show
    #clear search session value
    session[:journel_entries]["search"] = ""
    journel_entries = @journel.journel_entries
    @journel_entries_date = journel_entries.order(:created_at).group_by{|je| je.created_at.beginning_of_day}
    graph_data = {}
    @graph_data = prepare_graph_data(journel_entries)
  end

  def create
  	journel = AppJournel.new(journel_params)
  	
  	if journel.save
  		flash[:success] = "Journal created"
  	else
  		flash[:danger] = "Something went wrong"
  	end
  	redirect_to journels_path
  end

  def search_entries
    # Set search params in session, it will be used narrow the graph data
    session[:journel_entries]["search"] = params[:search]
    journel_entries = @journel.journel_entries.where('title like ?', "%#{params[:search]}%")
    @journel_entries_date = journel_entries.order(:created_at).group_by{|je| je.created_at.beginning_of_day}
    @graph_data = prepare_graph_data(journel_entries)
    render "show"
  end

  def search
    @journels = AppJournel.all.where('name like ?', "%#{params[:search]}%")
    render "index"
  end

  def graph_data
    if session[:journel_entries]["search"].present?
      journel_entries = @journel.journel_entries.where('title like ?', "%#{session[:journel_entries]["search"]}%")
    else
      journel_entries = @journel.journel_entries
    end 
    @graph_data = prepare_graph_data(journel_entries)
  end

  private

  def journel_params
  	params.require(:journel).permit(:name)
  end

  def set_journel
    @journel = AppJournel.find_by(id: params[:id])
  end

  def set_session
    session[:journel_entries] = session[:journel_entries] || {}
  end

  def prepare_graph_data(journel_entries)
    graph_data = {}
    if params[:graph_filter] == "w" || params[:graph_filter] == "m"
      data = journel_entries.group_by_day(:created_at, format: "%m/%d/%Y").count
      graph_data = {
        data: data,
        xtitle: "Days",
        ytitle: "Entries"
      }
    else
      data = journel_entries.group_by_month(:created_at, format: "%b %Y").count
      graph_data = {
        data: data,
        xtitle: "Months",
        ytitle: "Entries"
      }
    end
    graph_data
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/journel_entries_helper.rb
module JournelEntriesHelper
end

app/helpers/journels_helper.rb
module JournelsHelper
end

app/views/journel_entries/_create.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title">Add new Entry</h5>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>

    <%= form_with model: [ @journel, @journel.journel_entries.build ], url: journel_journel_entries_path, remote: false do |form| %>
      <div class="modal-body">
        <p>
          <%= form.label :title %><br>
          <%= form.text_field :title %>
        </p>
        <p>
            <%= form.label :body %><br>
            <%= form.text_area :body %>
        </p>
      </div>
      <div class="modal-footer">
        <%= form.submit "Save", class: "btn btn-primary" %>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    <% end %>
  </div>
</div>

app/views/journel_entries/_update.js.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title">Edit Entry</h5>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>

    <%= form_with model: [ @journel_entry.app_journel, @journel_entry ], url: journel_journel_entry_path, html: {method: "patch", remote: false} do |form| %>
      <div class="modal-body">
        <p>
          <%= form.label :title %><br>
          <%= form.text_field :title %>
        </p>
        <p>
            <%= form.label :body %><br>
            <%= form.text_area :body %>
        </p>
      </div>
      <div class="modal-footer">
        <%= form.submit "Save", class: "btn btn-primary" %>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    <% end %>
  </div>
</div>

app/views/journel_entries/edit.js.erb
$('#appModal').html("<%= j render(partial: "update") %>").modal('show');

app/views/journel_entries/new.js.erb
$('#appModal').html("<%= j render(partial: "create") %>").modal('show');

app/views/journel_entries/show.html.erb
<h1>Journal Entry</h1>
<strong>Title</strong>
<p><%= @journel_entry.title %></p>
<strong>Body</strong>
<p><%= @journel_entry.body %></p>
<%= link_to "Edit", edit_journel_journel_entry_path(journel_id: @journel_entry.app_journel.id, id: @journel_entry.id), class: "btn btn-outline-secondary mt-2",remote: true %>
<%= link_to "Back", journel_path(id: @journel_entry.app_journel.id), class: "btn btn-outline-secondary mt-2" %>

app/views/journels/_create.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title">Add new Journal</h5>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>

    <%= form_with scope: :journel, url: journels_path do |form| %>
      <div class="modal-body">
        <p>
          <%= form.label :name %><br>
          <%= form.text_field :name %>
        </p>
      </div>
      <div class="modal-footer">
        <%= form.submit "Save", class: "btn btn-primary" %>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    <% end %>
  </div>
</div>

app/views/journels/_graph.html.erb
<%= column_chart @graph_data[:data], xtitle: @graph_data[:xtitle], ytitle: @graph_data[:ytitle] %>

app/views/journels/graph_data.js.erb
$('#journel_entries_graph').html("<%= j render(partial: "graph") %>")

app/views/journels/index.html.erb
<h1>All Journals</h1>
<%= form_tag search_journels_path, method: 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", class: "btn btn-outline-primary" %>
  </p>
<% end %>
<% if @journels.any? %>
  <div class="w-50 p-1">
    <ul class="list-group list-group-flush">
      <% @journels.each do |journel| %>
        <li class="list-group-item"><%= link_to journel.name, journel_path(journel.id) %> </li>
      <% end %>
    </ul>
  </div>
<% else %>
  <p>Nothing is here yet!. Try adding new journels</p>
<% end %>
<%= link_to "New Journal", new_journel_path, class: "btn btn-outline-secondary mt-2",remote: true%>

app/views/journels/new.js.erb
$('#appModal').html("<%= j render(partial: "create") %>").modal('show');

app/views/journels/show.html.erb
<h1>Journal</h1>
<strong><%= @journel.name%></strong>
<strong><%= @journel.created_at.strftime("Created on %m/%d/%Y %H:%M:%S %Z") %></strong>
<hr/>
<h3>Entries</h3>
<%= form_tag search_entries_journel_path, method: 'get' do %>
    <p>
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag "Search", class: "btn btn-outline-primary" %>
    </p>
<% end %>

<h3>Graph</h3>
<%= form_tag(graph_data_journel_path, method: 'get', remote: true, id: "graph_form") do %>
    <%= select_tag(:graph_filter, options_for_select([["Week", 'w'], ["Month", "m"], ["Year", "y"], ["All", "a"]])) %>
    <%= submit_tag "Search", class: "btn btn-outline-primary" %>
<% end %>
<div class="w-50 mt-2", id="journel_entries_graph">
    <%= render partial: "graph" %>
</div>

<% if @journel_entries_date.any? %>
    <% @journel_entries_date.each do |date, journel_entries| %>
        <div class="w-50 p-1">
            <ul class="list-group list-group-flush">
                <% journel_entries.each do |je| %>
                    <li class="list-group-item">
                        <div>Title: <%= je.title %></div>
                        <div><%= je.created_at.strftime("Created on %m/%d/%Y %H:%M:%S %Z") %></div>
                        <div>Updated: <%= je.updated? ? "Yes" : "No" %></div>
                        <div><%= link_to "Details", journel_journel_entry_path(journel_id: @journel.id, id: je.id) %></div>
                    </li>
                <% end %>
            </ul>
        </div>
        </hr>
    <% end %>
<% else %>
    <p class="mt-3">Nothing is here yet!. Try adding new entries</p>
<% end %>

<%= link_to "New Entry", new_journel_journel_entry_path(journel_id: @journel.id), class: "btn btn-outline-secondary mt-2",remote: true %>
<%= link_to "Back", journels_path, class: "btn btn-outline-secondary mt-2" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Journal</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="container-fluid <%= params[:controller] %>-<%=params[:action]%>">
    <% flash.each do |name, msg| %>
      <div class= "mt-2 alert alert-<%= name %> alert-dismissible fades show" role="alert">
        <strong><%= msg %></strong>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
    <%= yield %>
    <div class="modal" id="appModal" tabindex="-1" role="dialog"></div>
  </body>
</html>